using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Velo.SQL.Models;

/// <summary>
/// A snapshot of a DORA dashboard, generated by "Share dashboard" so it can be handed
/// to people outside Azure DevOps (e.g. leadership) without giving them ADO access.
/// Intentionally NOT tenant-filtered — the public viewer endpoint has no org context to
/// filter by, since the whole point is that an unauthenticated visitor can open the link.
/// Ownership for mutation (revoke) is checked explicitly by comparing OrgId in the controller.
/// </summary>
[Table("SharedReports")]
public class SharedReport
{
    [Key]
    public Guid Id { get; set; } = Guid.NewGuid();

    [Required, MaxLength(100)]
    public string OrgId { get; set; } = string.Empty;

    [Required, MaxLength(200)]
    public string OrgDisplayName { get; set; } = string.Empty;

    [Required, MaxLength(100)]
    public string ProjectId { get; set; } = string.Empty;

    [MaxLength(200)]
    public string? RepositoryName { get; set; }

    /// <summary>Serialized <see cref="Velo.Shared.Models.DoraMetricsDto"/> at the time the link was created — a snapshot, not a live query.</summary>
    [Required]
    public string MetricsSnapshotJson { get; set; } = string.Empty;

    [MaxLength(256)]
    public string? CreatedBy { get; set; }

    public DateTimeOffset CreatedAt { get; set; } = DateTimeOffset.UtcNow;

    public DateTimeOffset ExpiresAt { get; set; }

    public DateTimeOffset? RevokedAt { get; set; }
}
